name: Docker image release

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ["v[0-9].[0-9]+.[0-9]+*"]


jobs:
  build-and-push:
    name: Build base image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: fozdoiguassu/hayhooks

      - name: Build base images
        uses: docker/bake-action@v5
        env:
          IMAGE_TAG_SUFFIX: ${{ steps.meta.outputs.version }}
          HAYHOOKS_VERSION: ${{ steps.meta.outputs.version }}
        with:
          workdir: docker
          push: true
